output-localization-file: retip_l10n.dart
required-resource-attributes: false
template-arb-file: l10n_en.arb
output-dir: lib/core/l10n
synthetic-package: false
output-class: RetipL10n
nullable-getter: false
arb-dir: l10n
format: true
