// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'app/data/models/album_model.dart';
import 'app/data/models/artist_model.dart';
import 'app/data/models/genre_model.dart';
import 'app/data/models/playlist_model.dart';
import 'app/data/models/track_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8237446563569716537),
    name: 'AlbumModel',
    lastPropertyId: const obx_int.IdUid(5, 5209097528547929076),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6845642157065356938),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4716621811126015929),
        name: 'albumId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(1, 7867007733970355455),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5731487062525176282),
        name: 'artistId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5169678303365118088),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5209097528547929076),
        name: 'artist',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4874773654772399362),
    name: 'ArtistModel',
    lastPropertyId: const obx_int.IdUid(3, 7628187968822500752),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4015673900654922376),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 91222287476829178),
        name: 'artistId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(2, 6583460287762243765),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7628187968822500752),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6382323524099676110),
    name: 'GenreModel',
    lastPropertyId: const obx_int.IdUid(3, 4837708670244950632),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5595068561796405854),
        name: 'genreId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6328813327814524507),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4837708670244950632),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5658743323260201565),
    name: 'PlaylistModel',
    lastPropertyId: const obx_int.IdUid(2, 4859212782934532248),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3698204168254405077),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4859212782934532248),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 6551605263038122284),
    name: 'TrackModel',
    lastPropertyId: const obx_int.IdUid(8, 5350968181059361588),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8001824126925008027),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 393263472713081668),
        name: 'trackId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(3, 3285564388563285517),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6907233859184040912),
        name: 'albumId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1127249654489023270),
        name: 'artistId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8685914394197528071),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4635576637299673212),
        name: 'album',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3423929537023055418),
        name: 'artist',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5350968181059361588),
        name: 'location',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 6084648827392694752),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 6551605263038122284),
    lastIndexId: const obx_int.IdUid(4, 6084648827392694752),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AlbumModel: obx_int.EntityDefinition<AlbumModel>(
      model: _entities[0],
      toOneRelations: (AlbumModel object) => [],
      toManyRelations: (AlbumModel object) => {},
      getId: (AlbumModel object) => object.id,
      setId: (AlbumModel object, int id) {
        object.id = id;
      },
      objectToFB: (AlbumModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final artistOffset = fbb.writeString(object.artist);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.albumId);
        fbb.addInt64(2, object.artistId);
        fbb.addOffset(3, titleOffset);
        fbb.addOffset(4, artistOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final albumIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final artistIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final artistParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = AlbumModel(
          id: idParam,
          albumId: albumIdParam,
          artistId: artistIdParam,
          title: titleParam,
          artist: artistParam,
        );

        return object;
      },
    ),
    ArtistModel: obx_int.EntityDefinition<ArtistModel>(
      model: _entities[1],
      toOneRelations: (ArtistModel object) => [],
      toManyRelations: (ArtistModel object) => {},
      getId: (ArtistModel object) => object.id,
      setId: (ArtistModel object, int id) {
        object.id = id;
      },
      objectToFB: (ArtistModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.artistId);
        fbb.addOffset(2, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final artistIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = ArtistModel(
          id: idParam,
          artistId: artistIdParam,
          name: nameParam,
        );

        return object;
      },
    ),
    GenreModel: obx_int.EntityDefinition<GenreModel>(
      model: _entities[2],
      toOneRelations: (GenreModel object) => [],
      toManyRelations: (GenreModel object) => {},
      getId: (GenreModel object) => object.id,
      setId: (GenreModel object, int id) {
        object.id = id;
      },
      objectToFB: (GenreModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.genreId);
        fbb.addInt64(1, object.id);
        fbb.addOffset(2, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final genreIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = GenreModel(
          id: idParam,
          genreId: genreIdParam,
          name: nameParam,
        );

        return object;
      },
    ),
    PlaylistModel: obx_int.EntityDefinition<PlaylistModel>(
      model: _entities[3],
      toOneRelations: (PlaylistModel object) => [],
      toManyRelations: (PlaylistModel object) => {},
      getId: (PlaylistModel object) => object.id,
      setId: (PlaylistModel object, int id) {
        object.id = id;
      },
      objectToFB: (PlaylistModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = PlaylistModel(id: idParam, name: nameParam);

        return object;
      },
    ),
    TrackModel: obx_int.EntityDefinition<TrackModel>(
      model: _entities[4],
      toOneRelations: (TrackModel object) => [],
      toManyRelations: (TrackModel object) => {},
      getId: (TrackModel object) => object.id,
      setId: (TrackModel object, int id) {
        object.id = id;
      },
      objectToFB: (TrackModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final albumOffset = fbb.writeString(object.album);
        final artistOffset = fbb.writeString(object.artist);
        final locationOffset = fbb.writeString(object.location);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.trackId);
        fbb.addInt64(2, object.albumId);
        fbb.addInt64(3, object.artistId);
        fbb.addOffset(4, titleOffset);
        fbb.addOffset(5, albumOffset);
        fbb.addOffset(6, artistOffset);
        fbb.addOffset(7, locationOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final trackIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final albumIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final artistIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final albumParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final artistParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final locationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object = TrackModel(
          id: idParam,
          trackId: trackIdParam,
          albumId: albumIdParam,
          artistId: artistIdParam,
          title: titleParam,
          album: albumParam,
          artist: artistParam,
          location: locationParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AlbumModel] entity fields to define ObjectBox queries.
class AlbumModel_ {
  /// See [AlbumModel.id].
  static final id = obx.QueryIntegerProperty<AlbumModel>(
    _entities[0].properties[0],
  );

  /// See [AlbumModel.albumId].
  static final albumId = obx.QueryIntegerProperty<AlbumModel>(
    _entities[0].properties[1],
  );

  /// See [AlbumModel.artistId].
  static final artistId = obx.QueryIntegerProperty<AlbumModel>(
    _entities[0].properties[2],
  );

  /// See [AlbumModel.title].
  static final title = obx.QueryStringProperty<AlbumModel>(
    _entities[0].properties[3],
  );

  /// See [AlbumModel.artist].
  static final artist = obx.QueryStringProperty<AlbumModel>(
    _entities[0].properties[4],
  );
}

/// [ArtistModel] entity fields to define ObjectBox queries.
class ArtistModel_ {
  /// See [ArtistModel.id].
  static final id = obx.QueryIntegerProperty<ArtistModel>(
    _entities[1].properties[0],
  );

  /// See [ArtistModel.artistId].
  static final artistId = obx.QueryIntegerProperty<ArtistModel>(
    _entities[1].properties[1],
  );

  /// See [ArtistModel.name].
  static final name = obx.QueryStringProperty<ArtistModel>(
    _entities[1].properties[2],
  );
}

/// [GenreModel] entity fields to define ObjectBox queries.
class GenreModel_ {
  /// See [GenreModel.genreId].
  static final genreId = obx.QueryIntegerProperty<GenreModel>(
    _entities[2].properties[0],
  );

  /// See [GenreModel.id].
  static final id = obx.QueryIntegerProperty<GenreModel>(
    _entities[2].properties[1],
  );

  /// See [GenreModel.name].
  static final name = obx.QueryStringProperty<GenreModel>(
    _entities[2].properties[2],
  );
}

/// [PlaylistModel] entity fields to define ObjectBox queries.
class PlaylistModel_ {
  /// See [PlaylistModel.id].
  static final id = obx.QueryIntegerProperty<PlaylistModel>(
    _entities[3].properties[0],
  );

  /// See [PlaylistModel.name].
  static final name = obx.QueryStringProperty<PlaylistModel>(
    _entities[3].properties[1],
  );
}

/// [TrackModel] entity fields to define ObjectBox queries.
class TrackModel_ {
  /// See [TrackModel.id].
  static final id = obx.QueryIntegerProperty<TrackModel>(
    _entities[4].properties[0],
  );

  /// See [TrackModel.trackId].
  static final trackId = obx.QueryIntegerProperty<TrackModel>(
    _entities[4].properties[1],
  );

  /// See [TrackModel.albumId].
  static final albumId = obx.QueryIntegerProperty<TrackModel>(
    _entities[4].properties[2],
  );

  /// See [TrackModel.artistId].
  static final artistId = obx.QueryIntegerProperty<TrackModel>(
    _entities[4].properties[3],
  );

  /// See [TrackModel.title].
  static final title = obx.QueryStringProperty<TrackModel>(
    _entities[4].properties[4],
  );

  /// See [TrackModel.album].
  static final album = obx.QueryStringProperty<TrackModel>(
    _entities[4].properties[5],
  );

  /// See [TrackModel.artist].
  static final artist = obx.QueryStringProperty<TrackModel>(
    _entities[4].properties[6],
  );

  /// See [TrackModel.location].
  static final location = obx.QueryStringProperty<TrackModel>(
    _entities[4].properties[7],
  );
}
