// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'app/data/models/track_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 7752318775264821867),
      name: 'TrackModel',
      lastPropertyId: const obx_int.IdUid(5, 3966078162657636586),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1327224383078804578),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4876302815174240193),
            name: 'artist',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8183575521074009946),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8340092925108959954),
            name: 'location',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 4031752736418694797)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3966078162657636586),
            name: 'isFavorite',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 7752318775264821867),
      lastIndexId: const obx_int.IdUid(1, 4031752736418694797),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    TrackModel: obx_int.EntityDefinition<TrackModel>(
        model: _entities[0],
        toOneRelations: (TrackModel object) => [],
        toManyRelations: (TrackModel object) => {},
        getId: (TrackModel object) => object.id,
        setId: (TrackModel object, int id) {
          object.id = id;
        },
        objectToFB: (TrackModel object, fb.Builder fbb) {
          final artistOffset = fbb.writeString(object.artist);
          final titleOffset = fbb.writeString(object.title);
          final locationOffset = fbb.writeString(object.location);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, artistOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addOffset(3, locationOffset);
          fbb.addBool(4, object.isFavorite);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final artistParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final locationParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final isFavoriteParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final object = TrackModel(
              id: idParam,
              artist: artistParam,
              title: titleParam,
              location: locationParam,
              isFavorite: isFavoriteParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [TrackModel] entity fields to define ObjectBox queries.
class TrackModel_ {
  /// See [TrackModel.id].
  static final id =
      obx.QueryIntegerProperty<TrackModel>(_entities[0].properties[0]);

  /// See [TrackModel.artist].
  static final artist =
      obx.QueryStringProperty<TrackModel>(_entities[0].properties[1]);

  /// See [TrackModel.title].
  static final title =
      obx.QueryStringProperty<TrackModel>(_entities[0].properties[2]);

  /// See [TrackModel.location].
  static final location =
      obx.QueryStringProperty<TrackModel>(_entities[0].properties[3]);

  /// See [TrackModel.isFavorite].
  static final isFavorite =
      obx.QueryBooleanProperty<TrackModel>(_entities[0].properties[4]);
}
