// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../../../app/data/models/album_model.dart';
import '../../../../app/data/models/track_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2161671807308400359),
    name: 'TrackModel',
    lastPropertyId: const obx_int.IdUid(5, 7739210875802611740),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2193778789188433018),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 295842122658383785),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6981179420116841423),
        name: 'artist',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8037833732572983422),
        name: 'trackId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(1, 2536600317392185976),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7739210875802611740),
        name: 'albumId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6118774961528983994),
    name: 'AlbumModel',
    lastPropertyId: const obx_int.IdUid(4, 2111785886942245912),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2476487014999892732),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6612809907530308117),
        name: 'albumId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(3, 1199251093540181512),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9010638221740832179),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2111785886942245912),
        name: 'artist',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 6118774961528983994),
    lastIndexId: const obx_int.IdUid(3, 1199251093540181512),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [2383807460955450220],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      5985783947908702206,
      724831132867881327,
      7804203479136991273,
      7973832987709364854,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    TrackModel: obx_int.EntityDefinition<TrackModel>(
      model: _entities[0],
      toOneRelations: (TrackModel object) => [],
      toManyRelations: (TrackModel object) => {},
      getId: (TrackModel object) => object.id,
      setId: (TrackModel object, int id) {
        object.id = id;
      },
      objectToFB: (TrackModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final artistOffset = fbb.writeString(object.artist);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, artistOffset);
        fbb.addInt64(3, object.trackId);
        fbb.addInt64(4, object.albumId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final trackIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final albumIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final artistParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = TrackModel(
          id: idParam,
          trackId: trackIdParam,
          albumId: albumIdParam,
          title: titleParam,
          artist: artistParam,
        );

        return object;
      },
    ),
    AlbumModel: obx_int.EntityDefinition<AlbumModel>(
      model: _entities[1],
      toOneRelations: (AlbumModel object) => [],
      toManyRelations: (AlbumModel object) => {},
      getId: (AlbumModel object) => object.id,
      setId: (AlbumModel object, int id) {
        object.id = id;
      },
      objectToFB: (AlbumModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final artistOffset = fbb.writeString(object.artist);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.albumId);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, artistOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final albumIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final artistParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = AlbumModel(
          id: idParam,
          albumId: albumIdParam,
          title: titleParam,
          artist: artistParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [TrackModel] entity fields to define ObjectBox queries.
class TrackModel_ {
  /// See [TrackModel.id].
  static final id = obx.QueryIntegerProperty<TrackModel>(
    _entities[0].properties[0],
  );

  /// See [TrackModel.title].
  static final title = obx.QueryStringProperty<TrackModel>(
    _entities[0].properties[1],
  );

  /// See [TrackModel.artist].
  static final artist = obx.QueryStringProperty<TrackModel>(
    _entities[0].properties[2],
  );

  /// See [TrackModel.trackId].
  static final trackId = obx.QueryIntegerProperty<TrackModel>(
    _entities[0].properties[3],
  );

  /// See [TrackModel.albumId].
  static final albumId = obx.QueryIntegerProperty<TrackModel>(
    _entities[0].properties[4],
  );
}

/// [AlbumModel] entity fields to define ObjectBox queries.
class AlbumModel_ {
  /// See [AlbumModel.id].
  static final id = obx.QueryIntegerProperty<AlbumModel>(
    _entities[1].properties[0],
  );

  /// See [AlbumModel.albumId].
  static final albumId = obx.QueryIntegerProperty<AlbumModel>(
    _entities[1].properties[1],
  );

  /// See [AlbumModel.title].
  static final title = obx.QueryStringProperty<AlbumModel>(
    _entities[1].properties[2],
  );

  /// See [AlbumModel.artist].
  static final artist = obx.QueryStringProperty<AlbumModel>(
    _entities[1].properties[3],
  );
}
